### ISSUE TITLE
Simulated vs estimated contract plot

### ISSUE THREAD

**Issue by taqtiqa-mark** [peilun-he/PDSim#21]
The plots in the [Tests section](https://github.com/peilun-he/PDSim?tab=readme-ov-file#tests) can be improved by:

1. Starting the simulations from a common initial value
2. Using the same simulated values of the dW pair
3. Providing a third plot showing the SS and FP sample paths together,  for the same simulated innovations and initial values.

**Comment by peilun-he** [comment]
A plot of sample paths from Schwartz Smith model and polynomial diffusion model using same parameters and innovations is added: https://github.com/peilun-he/PDSim/commit/091cbeb9c9f803c15cf613ee552c91b2d499741f

**Comment by taqtiqa-mark** [comment]
I had added a comment previously, just calling it out in case it did not trigger a GH notification:

https://github.com/peilun-he/PDSim/commit/091cbeb9c9f803c15cf613ee552c91b2d499741f#commitcomment-138492536

**Comment by peilun-he** [comment]
For the simulated sample paths: https://github.com/peilun-he/PDSim/commit/091cbeb9c9f803c15cf613ee552c91b2d499741f#commitcomment-138765359

**Comment by taqtiqa-mark** [comment]
I've also added comments to this commit:

https://github.com/peilun-he/PDSim/commit/c5ece915f0620f16a56beb38dbacf9ad75806d05

**Comment by peilun-he** [comment]
Some updates according to your suggestions: https://github.com/peilun-he/PDSim/commit/fa01e27493c6bd0f44ec5c35f3046f3545d94d2e. 

If $\alpha_4 = \alpha_5 = \alpha_6 = 0$, the difference of futures prices is exactly 1. 

I also added a new section about the convergence of the spot prices. This demonstrate that when some coefficients converge to 0, the simulated spot prices from two models converge to each other.

**Comment by peilun-he** [comment]
Sorry please ignore the part about spot prices for now. I will need to make further clarifications. 
I apologise.

**Comment by peilun-he** [comment]
Dear Prof. Van de Vyver,

This is a response from Prof. Peters in consultation with the corresponding author Mr. He, intended to clarify aspects of this response to your request regarding the figures in the testing section. 

Please allow us to clarify some remaining items of consideration: 
1. The figures referred to SS model and polynomial diffusion model test results do in fact have the same state initialisation. However, what is plotted is the futures price for each model. Since the model are not the same, these plots will never match at the same value. Please note that this does not mean that we cannot use these results for confirmation of the implementation of each model. An argument is made for the justification of our approach in our response to related suggestions please see: #14 . 
2. Regarding "Using the same simulated values of the dW pair", this was performed as part of the study referred to item 1 above. 
3. Regarding "Providing a third plot showing the SS and FP sample paths together, for the same simulated innovations and initial values", given the additional insights we have commented about in our response (#14 ), it should be apparent that this is not a viable plot that would be of value for the intended purpose. Instead we have provided the alternative plots and illustrations that we believe achieve the desired objective (see discussion in #14). 

Both Mr. He and co-authors deeply appreciate your time and consideration on this review and we hope that we have clarified the justification for our response to this request. Of course, if there are any additional aspects you wish to see we are more than happy to work with you to finalise this review as needed.

**Comment by taqtiqa-mark** [comment]
Thank you for the update.  Hopefully this suggestion focuses attention on the issues.

1. Please reproduce Figure 4. from the original SS paper.
   1. Note this does not replace the requirement to reproduce Figure 1 from the same paper
   2. I understand these models can be subtle, and have 'unusual' objects in them.  That needs to be called out in the user documentation and reflected in the UI for 'unsuspecting' users.
   3. To assist I have found another project where the author has produced what one would naturally expect.  You really just need to follow his code to produce the Fig 4 replication he has:
     - https://www.mathworks.com/matlabcentral/fileexchange/29745-simulation-of-schwartz-smith-two-factor-model?s_tid=FX_rc3_behav
    4. Please produce a similar figure for the FP model, specifically showing the same objects as the Goodwin SS replication.
 1. Please update your simulated SS and FP to show the same series shown in Goodwin's work
 
Hopefully you'll agree the current simulations are entirely inadequate and miss the point of these models.  
To be clear, I am not suggesting this confusion bars publication - we all learn somehow - and this is an entirely technical exercise of simulating and estimating.  

However, you did chose the make financial applications the focus of your paper, so it is reasonable that you at least produce the core features of the models.

That said, this submission is not a venue for a basic course in Finance and I have exhausted my free time I willing to devote to this.

Please only update these issues when you believe you have implemented what I have suggested is need. Or ask an editor to disregard the suggestions.

**Comment by peilun-he** [comment]
Figure 4 has been reproduced in the "Replicating Schwartz and Smith's Results" section for both the Schwartz and Smith model (3rd and 4th plots) and the polynomial diffusion model (5th and 6th plots). However, due to the unavailability of the same data (1990 - 1996) as Schwartz and Smith, we utilised simulated data from their estimations. Additionally, we divided Figure 4 from Schwartz and Smith's paper into two plots for each model to clearly display the confidence interval.
